// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: gnd.proto
// </auto-generated>
#pragma warning disable 0414, 1591, 8981, 0612
#region Designer generated code

using grpc = global::Grpc.Core;

namespace Gnd.Windows.Grpc {
  public static partial class GndService
  {
    static readonly string __ServiceName = "gnd.GndService";

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static void __Helper_SerializeMessage(global::Google.Protobuf.IMessage message, grpc::SerializationContext context)
    {
      #if !GRPC_DISABLE_PROTOBUF_BUFFER_SERIALIZATION
      if (message is global::Google.Protobuf.IBufferMessage)
      {
        context.SetPayloadLength(message.CalculateSize());
        global::Google.Protobuf.MessageExtensions.WriteTo(message, context.GetBufferWriter());
        context.Complete();
        return;
      }
      #endif
      context.Complete(global::Google.Protobuf.MessageExtensions.ToByteArray(message));
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static class __Helper_MessageCache<T>
    {
      public static readonly bool IsBufferMessage = global::System.Reflection.IntrospectionExtensions.GetTypeInfo(typeof(global::Google.Protobuf.IBufferMessage)).IsAssignableFrom(typeof(T));
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static T __Helper_DeserializeMessage<T>(grpc::DeserializationContext context, global::Google.Protobuf.MessageParser<T> parser) where T : global::Google.Protobuf.IMessage<T>
    {
      #if !GRPC_DISABLE_PROTOBUF_BUFFER_SERIALIZATION
      if (__Helper_MessageCache<T>.IsBufferMessage)
      {
        return parser.ParseFrom(context.PayloadAsReadOnlySequence());
      }
      #endif
      return parser.ParseFrom(context.PayloadAsNewBuffer());
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Gnd.Windows.Grpc.StartDiscoveryRequest> __Marshaller_gnd_StartDiscoveryRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Gnd.Windows.Grpc.StartDiscoveryRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Gnd.Windows.Grpc.StartDiscoveryResponse> __Marshaller_gnd_StartDiscoveryResponse = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Gnd.Windows.Grpc.StartDiscoveryResponse.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Gnd.Windows.Grpc.StopDiscoveryRequest> __Marshaller_gnd_StopDiscoveryRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Gnd.Windows.Grpc.StopDiscoveryRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Gnd.Windows.Grpc.StopDiscoveryResponse> __Marshaller_gnd_StopDiscoveryResponse = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Gnd.Windows.Grpc.StopDiscoveryResponse.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Gnd.Windows.Grpc.GetDevicesRequest> __Marshaller_gnd_GetDevicesRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Gnd.Windows.Grpc.GetDevicesRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Gnd.Windows.Grpc.GetDevicesResponse> __Marshaller_gnd_GetDevicesResponse = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Gnd.Windows.Grpc.GetDevicesResponse.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Gnd.Windows.Grpc.ConnectRequest> __Marshaller_gnd_ConnectRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Gnd.Windows.Grpc.ConnectRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Gnd.Windows.Grpc.ConnectResponse> __Marshaller_gnd_ConnectResponse = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Gnd.Windows.Grpc.ConnectResponse.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Gnd.Windows.Grpc.DisconnectRequest> __Marshaller_gnd_DisconnectRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Gnd.Windows.Grpc.DisconnectRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Gnd.Windows.Grpc.DisconnectResponse> __Marshaller_gnd_DisconnectResponse = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Gnd.Windows.Grpc.DisconnectResponse.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Gnd.Windows.Grpc.StartStreamRequest> __Marshaller_gnd_StartStreamRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Gnd.Windows.Grpc.StartStreamRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Gnd.Windows.Grpc.StartStreamResponse> __Marshaller_gnd_StartStreamResponse = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Gnd.Windows.Grpc.StartStreamResponse.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Gnd.Windows.Grpc.StopStreamRequest> __Marshaller_gnd_StopStreamRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Gnd.Windows.Grpc.StopStreamRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Gnd.Windows.Grpc.StopStreamResponse> __Marshaller_gnd_StopStreamResponse = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Gnd.Windows.Grpc.StopStreamResponse.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Gnd.Windows.Grpc.StreamEventsRequest> __Marshaller_gnd_StreamEventsRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Gnd.Windows.Grpc.StreamEventsRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Gnd.Windows.Grpc.DeviceEvent> __Marshaller_gnd_DeviceEvent = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Gnd.Windows.Grpc.DeviceEvent.Parser));

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::Gnd.Windows.Grpc.StartDiscoveryRequest, global::Gnd.Windows.Grpc.StartDiscoveryResponse> __Method_StartDiscovery = new grpc::Method<global::Gnd.Windows.Grpc.StartDiscoveryRequest, global::Gnd.Windows.Grpc.StartDiscoveryResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "StartDiscovery",
        __Marshaller_gnd_StartDiscoveryRequest,
        __Marshaller_gnd_StartDiscoveryResponse);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::Gnd.Windows.Grpc.StopDiscoveryRequest, global::Gnd.Windows.Grpc.StopDiscoveryResponse> __Method_StopDiscovery = new grpc::Method<global::Gnd.Windows.Grpc.StopDiscoveryRequest, global::Gnd.Windows.Grpc.StopDiscoveryResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "StopDiscovery",
        __Marshaller_gnd_StopDiscoveryRequest,
        __Marshaller_gnd_StopDiscoveryResponse);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::Gnd.Windows.Grpc.GetDevicesRequest, global::Gnd.Windows.Grpc.GetDevicesResponse> __Method_GetDevices = new grpc::Method<global::Gnd.Windows.Grpc.GetDevicesRequest, global::Gnd.Windows.Grpc.GetDevicesResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "GetDevices",
        __Marshaller_gnd_GetDevicesRequest,
        __Marshaller_gnd_GetDevicesResponse);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::Gnd.Windows.Grpc.ConnectRequest, global::Gnd.Windows.Grpc.ConnectResponse> __Method_Connect = new grpc::Method<global::Gnd.Windows.Grpc.ConnectRequest, global::Gnd.Windows.Grpc.ConnectResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "Connect",
        __Marshaller_gnd_ConnectRequest,
        __Marshaller_gnd_ConnectResponse);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::Gnd.Windows.Grpc.DisconnectRequest, global::Gnd.Windows.Grpc.DisconnectResponse> __Method_Disconnect = new grpc::Method<global::Gnd.Windows.Grpc.DisconnectRequest, global::Gnd.Windows.Grpc.DisconnectResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "Disconnect",
        __Marshaller_gnd_DisconnectRequest,
        __Marshaller_gnd_DisconnectResponse);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::Gnd.Windows.Grpc.StartStreamRequest, global::Gnd.Windows.Grpc.StartStreamResponse> __Method_StartStream = new grpc::Method<global::Gnd.Windows.Grpc.StartStreamRequest, global::Gnd.Windows.Grpc.StartStreamResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "StartStream",
        __Marshaller_gnd_StartStreamRequest,
        __Marshaller_gnd_StartStreamResponse);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::Gnd.Windows.Grpc.StopStreamRequest, global::Gnd.Windows.Grpc.StopStreamResponse> __Method_StopStream = new grpc::Method<global::Gnd.Windows.Grpc.StopStreamRequest, global::Gnd.Windows.Grpc.StopStreamResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "StopStream",
        __Marshaller_gnd_StopStreamRequest,
        __Marshaller_gnd_StopStreamResponse);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::Gnd.Windows.Grpc.StreamEventsRequest, global::Gnd.Windows.Grpc.DeviceEvent> __Method_StreamEvents = new grpc::Method<global::Gnd.Windows.Grpc.StreamEventsRequest, global::Gnd.Windows.Grpc.DeviceEvent>(
        grpc::MethodType.ServerStreaming,
        __ServiceName,
        "StreamEvents",
        __Marshaller_gnd_StreamEventsRequest,
        __Marshaller_gnd_DeviceEvent);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::Gnd.Windows.Grpc.GndReflection.Descriptor.Services[0]; }
    }

    /// <summary>Base class for server-side implementations of GndService</summary>
    [grpc::BindServiceMethod(typeof(GndService), "BindService")]
    public abstract partial class GndServiceBase
    {
      /// <summary>
      /// Device discovery
      /// </summary>
      /// <param name="request">The request received from the client.</param>
      /// <param name="context">The context of the server-side call handler being invoked.</param>
      /// <returns>The response to send back to the client (wrapped by a task).</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::Gnd.Windows.Grpc.StartDiscoveryResponse> StartDiscovery(global::Gnd.Windows.Grpc.StartDiscoveryRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::Gnd.Windows.Grpc.StopDiscoveryResponse> StopDiscovery(global::Gnd.Windows.Grpc.StopDiscoveryRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::Gnd.Windows.Grpc.GetDevicesResponse> GetDevices(global::Gnd.Windows.Grpc.GetDevicesRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      /// <summary>
      /// Device connection
      /// </summary>
      /// <param name="request">The request received from the client.</param>
      /// <param name="context">The context of the server-side call handler being invoked.</param>
      /// <returns>The response to send back to the client (wrapped by a task).</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::Gnd.Windows.Grpc.ConnectResponse> Connect(global::Gnd.Windows.Grpc.ConnectRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::Gnd.Windows.Grpc.DisconnectResponse> Disconnect(global::Gnd.Windows.Grpc.DisconnectRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      /// <summary>
      /// Streaming
      /// </summary>
      /// <param name="request">The request received from the client.</param>
      /// <param name="context">The context of the server-side call handler being invoked.</param>
      /// <returns>The response to send back to the client (wrapped by a task).</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::Gnd.Windows.Grpc.StartStreamResponse> StartStream(global::Gnd.Windows.Grpc.StartStreamRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::Gnd.Windows.Grpc.StopStreamResponse> StopStream(global::Gnd.Windows.Grpc.StopStreamRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      /// <summary>
      /// Event subscriptions
      /// </summary>
      /// <param name="request">The request received from the client.</param>
      /// <param name="responseStream">Used for sending responses back to the client.</param>
      /// <param name="context">The context of the server-side call handler being invoked.</param>
      /// <returns>A task indicating completion of the handler.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task StreamEvents(global::Gnd.Windows.Grpc.StreamEventsRequest request, grpc::IServerStreamWriter<global::Gnd.Windows.Grpc.DeviceEvent> responseStream, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    public static grpc::ServerServiceDefinition BindService(GndServiceBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_StartDiscovery, serviceImpl.StartDiscovery)
          .AddMethod(__Method_StopDiscovery, serviceImpl.StopDiscovery)
          .AddMethod(__Method_GetDevices, serviceImpl.GetDevices)
          .AddMethod(__Method_Connect, serviceImpl.Connect)
          .AddMethod(__Method_Disconnect, serviceImpl.Disconnect)
          .AddMethod(__Method_StartStream, serviceImpl.StartStream)
          .AddMethod(__Method_StopStream, serviceImpl.StopStream)
          .AddMethod(__Method_StreamEvents, serviceImpl.StreamEvents).Build();
    }

    /// <summary>Register service method with a service binder with or without implementation. Useful when customizing the service binding logic.
    /// Note: this method is part of an experimental API that can change or be removed without any prior notice.</summary>
    /// <param name="serviceBinder">Service methods will be bound by calling <c>AddMethod</c> on this object.</param>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    public static void BindService(grpc::ServiceBinderBase serviceBinder, GndServiceBase serviceImpl)
    {
      serviceBinder.AddMethod(__Method_StartDiscovery, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Gnd.Windows.Grpc.StartDiscoveryRequest, global::Gnd.Windows.Grpc.StartDiscoveryResponse>(serviceImpl.StartDiscovery));
      serviceBinder.AddMethod(__Method_StopDiscovery, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Gnd.Windows.Grpc.StopDiscoveryRequest, global::Gnd.Windows.Grpc.StopDiscoveryResponse>(serviceImpl.StopDiscovery));
      serviceBinder.AddMethod(__Method_GetDevices, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Gnd.Windows.Grpc.GetDevicesRequest, global::Gnd.Windows.Grpc.GetDevicesResponse>(serviceImpl.GetDevices));
      serviceBinder.AddMethod(__Method_Connect, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Gnd.Windows.Grpc.ConnectRequest, global::Gnd.Windows.Grpc.ConnectResponse>(serviceImpl.Connect));
      serviceBinder.AddMethod(__Method_Disconnect, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Gnd.Windows.Grpc.DisconnectRequest, global::Gnd.Windows.Grpc.DisconnectResponse>(serviceImpl.Disconnect));
      serviceBinder.AddMethod(__Method_StartStream, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Gnd.Windows.Grpc.StartStreamRequest, global::Gnd.Windows.Grpc.StartStreamResponse>(serviceImpl.StartStream));
      serviceBinder.AddMethod(__Method_StopStream, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Gnd.Windows.Grpc.StopStreamRequest, global::Gnd.Windows.Grpc.StopStreamResponse>(serviceImpl.StopStream));
      serviceBinder.AddMethod(__Method_StreamEvents, serviceImpl == null ? null : new grpc::ServerStreamingServerMethod<global::Gnd.Windows.Grpc.StreamEventsRequest, global::Gnd.Windows.Grpc.DeviceEvent>(serviceImpl.StreamEvents));
    }

  }
}
#endregion
